services:
  - type: web
    name: web-chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: web-chat-db
          property: connectionString
    databases:
      - name: web-chat-db
        databaseName: chatdb
        user: chatuser

databases:
  - name: web-chat-db
